drop database dbEmpresa;
create database dbEmpresa;
use dbEmpresa;

CREATE TABLE PRODUTOS( 
 CODIGO INT, 
 NOME VARCHAR(50), 
 TIPO VARCHAR(25), 
 QUANTIDADE INT, 
 VALOR DECIMAL(10,2) 
);

INSERT INTO PRODUTOS ( CODIGO, NOME, TIPO, QUANTIDADE, VALOR ) VALUES ( 1,'IMPRESSORA', 'INFORMATICA', 200, 600.00 );
INSERT INTO PRODUTOS ( CODIGO, NOME, TIPO, QUANTIDADE, VALOR ) VALUES ( 2,'CAMERA DIGITAL', 'DIGITAIS', 300, 400.00 );
INSERT INTO PRODUTOS ( CODIGO, NOME, TIPO, QUANTIDADE, VALOR ) VALUES ( 3, 'DVD PLAYER', 'ELETRONICOS', 250, 500.00 );
INSERT INTO PRODUTOS ( CODIGO, NOME, TIPO, QUANTIDADE, VALOR ) VALUES ( 4,'MONITOR', 'INFORMATICA', 400, 900.00 );
INSERT INTO PRODUTOS ( CODIGO, NOME, TIPO, QUANTIDADE, VALOR ) VALUES ( 5,'TELEVISOR', 'ELETRONICOS', 350, 650.00 ); 
INSERT INTO PRODUTOS ( CODIGO, NOME, TIPO, QUANTIDADE, VALOR ) VALUES ( 6,'FILMADORA DIGITAL', 'DIGITAIS', 500, 700.00 ); 
INSERT INTO PRODUTOS ( CODIGO, NOME, TIPO, QUANTIDADE, VALOR ) VALUES ( 7,'CELULAR', 'TELEFONE', 450, 850.00 ); 
INSERT INTO PRODUTOS ( CODIGO, NOME, TIPO, QUANTIDADE, VALOR ) VALUES ( 8,'TECLADO', 'INFORMATICA', 300, 450.00 ); 
INSERT INTO PRODUTOS ( CODIGO, NOME, TIPO, QUANTIDADE, VALOR ) VALUES ( 9,'VIDEOCASSETE', 'ELETRONICOS', 200, 300.00 ); 
INSERT INTO PRODUTOS ( CODIGO, NOME, TIPO, QUANTIDADE, VALOR ) VALUES ( 10,'MOUSE', 'INFORMATICA', 400, 60.0);

desc PRODUTOS;

select * from PRODUTOS;


-- clausula WHERE
update produtos set valor = valor*1.15 where tipo = 'informatica';

-- clausula AND
UPDATE PRODUTOS SET VALOR = VALOR * 1.05 WHERE TIPO = 'ELETRONICOS' AND VALOR < 600.00;

-- clausula OR
UPDATE PRODUTOS SET VALOR = VALOR * 0.80 WHERE TIPO = 'DIGITAIS' OR VALOR > 1000.00;

-- clausula IN
SELECT * FROM PRODUTOS WHERE TIPO IN ('INFORMATICA', 'DIGITAIS')

-- clausula BETWEEN
select * from produtos where valor between 400.00 and 700.00;

-- clausula NOT BETWEEN
select * from produtos where valor not between 300.00 and 500.00;

-- clausula LIKE
select * from produtos where nome like 't%';

-- clausula ORDE BY
select * from produtos order by valor;
-- clausula ORDER BY DESC( forma decrescente)
select * from produtos order by valor desc;
-- clausula limit
select * from produtos limit 5;
